In [7]:
# 사용자-아이템 행렬 (1: 선호, -1: 비선호, 0: 평가 없음)
user_item_matrix = np.array([
    [1, 0, -1, 0],  # 사용자 1
    [1, -1, 0, 1],  # 사용자 2
    [0, 1, 1, 0],   # 사용자 3
    [-1, 0, 0, 1]   # 사용자 4
])

# 코사인 유사도 계산 함수
def cosine_similarity(matrix):
    item_count = matrix.shape[1]
    similarity_matrix = np.zeros((item_count, item_count))

    for i in range(item_count):
        for j in range(item_count):
            if i == j:
                similarity_matrix[i, j] = 1  # 자기 자신과의 유사도는 1
            else:
                dot_product = np.dot(matrix[:, i], matrix[:, j])
                norm_i = np.linalg.norm(matrix[:, i])
                norm_j = np.linalg.norm(matrix[:, j])
                
                if norm_i > 0 and norm_j > 0:
                    similarity_matrix[i, j] = dot_product / (norm_i * norm_j)
                else:
                    similarity_matrix[i, j] = 0

    return similarity_matrix

# 코사인 유사도 계산 함수
def cosine_similarity(matrix):
    item_count = matrix.shape[1]
    similarity_matrix = np.zeros((item_count, item_count))

    for i in range(item_count):
        for j in range(item_count):
            if i == j:
                similarity_matrix[i, j] = 1  # 자기 자신과의 유사도는 1
            else:
                dot_product = np.dot(matrix[:, i], matrix[:, j])
                norm_i = np.linalg.norm(matrix[:, i])
                norm_j = np.linalg.norm(matrix[:, j])
                
                if norm_i > 0 and norm_j > 0:
                    similarity_matrix[i, j] = dot_product / (norm_i * norm_j)
                else:
                    similarity_matrix[i, j] = 0

    return similarity_matrix

# 선호 예측 함수
def predict_preferences(user_item_matrix, similarity_matrix):
    predictions = np.zeros_like(user_item_matrix)
    predicted_values = []  # 예측된 값 리스트
    actual_values_list = []  # 실제 값 리스트

    for user in range(user_item_matrix.shape[0]):
        for item in range(user_item_matrix.shape[1]):
            if user_item_matrix[user, item] != 0:  # 평가가 있는 경우는 건너뜀
                continue

            # 평가가 없는 경우에 대해 예측
            similar_items = similarity_matrix[item]
            weighted_sum = np.dot(similar_items, user_item_matrix[user, :])
            normalization_factor = np.sum(np.abs(similar_items[similar_items > 0]))  # 가중치의 합
            if normalization_factor > 0:
                prediction = weighted_sum / normalization_factor
                # 예측값을 1 또는 -1로 변환
                predicted_value = 1 if prediction > 0 else -1
                predictions[user, item] = predicted_value
                
                # 리스트에 예측값과 실제값 저장
                predicted_values.append(predicted_value)
                actual_values_list.append(actual_values[user, item])

    return predictions, predicted_values, actual_values_list

# 정확도 계산 함수
def calculate_accuracy(predicted_values, actual_values_list):
    correct_predictions = sum(p == a for p, a in zip(predicted_values, actual_values_list))
    total_predictions = len(actual_values_list)

    if total_predictions == 0:
        return 0  # 평가가 없으면 정확도 0
    return correct_predictions / total_predictions

# 코사인 유사도 행렬 생성
similarity_matrix = cosine_similarity(user_item_matrix)

# 선호 예측 수행
predictions, predicted_values, actual_values_list = predict_preferences(user_item_matrix, similarity_matrix)

# 정확도 계산
accuracy = calculate_accuracy(predicted_values, actual_values_list)

# 결과 출력
print("코사인 유사도 행렬:")
print(similarity_matrix)
print("예측된 선호도 행렬:")
print(predictions)
print("예측된 값 리스트:", predicted_values)
print("실제 값 리스트:", actual_values_list)
print(f"정확도: {accuracy:.2f}")


코사인 유사도 행렬:
[[ 1.         -0.40824829 -0.40824829  0.        ]
 [-0.40824829  1.          0.5        -0.5       ]
 [-0.40824829  0.5         1.          0.        ]
 [ 0.         -0.5         0.          1.        ]]
예측된 선호도 행렬:
[[ 0 -1  0 -1]
 [ 0  0 -1  0]
 [-1  0  0 -1]
 [ 0 -1  1  0]]
예측된 값 리스트: [-1, -1, -1, -1, -1, -1, 1]
실제 값 리스트: [1, -1, 1, 1, -1, -1, 1]
정확도: 0.57


In [8]:
import numpy as np

# 사용자-아이템 행렬 (1: 선호, -1: 비선호, 0: 평가 없음)
# 실제 값이지만 평가가 없다고 가정
user_item_matrix = np.array([
    [1, 0, -1, 0],  # 사용자 1
    [1, -1, 0, 1],  # 사용자 2
    [0, 1, 1, 0],   # 사용자 3
    [-1, 0, 0, 1]   # 사용자 4
])

# 실제 값 (평가가 없던 아이템에 대한 실제 값)
actual_values = np.array([
    [1, 1, -1, -1],  # 사용자 1에 대한 실제 값
    [1, -1, 1, 1],  # 사용자 2에 대한 실제 값
    [1, 1, 1, -1],  # 사용자 3에 대한 실제 값
    [-1, -1, 1, 1]   # 사용자 4에 대한 실제 값
])


# 코사인 유사도 계산 함수
def cosine_similarity(matrix):
    item_count = matrix.shape[1]
    similarity_matrix = np.zeros((item_count, item_count))

    for i in range(item_count):
        for j in range(item_count):
            if i == j:
                similarity_matrix[i, j] = 1  # 자기 자신과의 유사도는 1
            else:
                dot_product = np.dot(matrix[:, i], matrix[:, j])
                norm_i = np.linalg.norm(matrix[:, i])
                norm_j = np.linalg.norm(matrix[:, j])
                
                if norm_i > 0 and norm_j > 0:
                    similarity_matrix[i, j] = dot_product / (norm_i * norm_j)
                else:
                    similarity_matrix[i, j] = 0

    return similarity_matrix

# 선호 예측 함수
def predict_preferences(user_item_matrix, similarity_matrix):
    predictions = np.zeros_like(user_item_matrix)
    predicted_values = []  # 예측된 값 리스트
    actual_values_list = []  # 실제 값 리스트

    for user in range(user_item_matrix.shape[0]):
        for item in range(user_item_matrix.shape[1]):
            if user_item_matrix[user, item] != 0:  # 평가가 있는 경우는 건너뜀
                continue

            # 평가가 없는 경우에 대해 예측
            similar_items = similarity_matrix[item]
            weighted_sum = np.dot(similar_items, user_item_matrix[user, :])
            normalization_factor = np.sum(np.abs(similar_items[similar_items > 0]))  # 가중치의 합
            if normalization_factor > 0:
                prediction = weighted_sum / normalization_factor
                # 예측값을 1 또는 -1로 변환
                predicted_value = 1 if prediction > 0 else -1
                predictions[user, item] = predicted_value
                
                # 리스트에 예측값과 실제값 저장
                predicted_values.append(predicted_value)
                actual_values_list.append(actual_values[user, item])

    return predictions, predicted_values, actual_values_list

# 정확도 계산 함수
def calculate_accuracy(predicted_values, actual_values_list):
    correct_predictions = sum(p == a for p, a in zip(predicted_values, actual_values_list))
    total_predictions = len(actual_values_list)

    if total_predictions == 0:
        return 0  # 평가가 없으면 정확도 0
    return correct_predictions / total_predictions

# 코사인 유사도 행렬 생성
similarity_matrix = cosine_similarity(user_item_matrix)

# 선호 예측 수행
predictions, predicted_values, actual_values_list = predict_preferences(user_item_matrix, similarity_matrix)

# 정확도 계산
accuracy = calculate_accuracy(predicted_values, actual_values_list)

# 결과 출력
print("코사인 유사도 행렬:")
print(similarity_matrix)
print("예측된 선호도 행렬:")
print(predictions)
print("예측된 값 리스트:", predicted_values)
print("실제 값 리스트:", actual_values_list)
print(f"정확도: {accuracy:.2f}")


코사인 유사도 행렬:
[[ 1.         -0.40824829 -0.40824829  0.        ]
 [-0.40824829  1.          0.5        -0.5       ]
 [-0.40824829  0.5         1.          0.        ]
 [ 0.         -0.5         0.          1.        ]]
예측된 선호도 행렬:
[[ 0 -1  0 -1]
 [ 0  0 -1  0]
 [-1  0  0 -1]
 [ 0 -1  1  0]]
예측된 값 리스트: [-1, -1, -1, -1, -1, -1, 1]
실제 값 리스트: [1, -1, 1, 1, -1, -1, 1]
정확도: 0.57


In [10]:
# 사용자-아이템 행렬 (1: 선호, -1: 비선호, 0: validation)
user_item_matrix = np.array([
    [1, 0, -1, 0],  # 사용자 1
    [1, -1, 0, 1],  # 사용자 2
    [0, 1, 1, 0],   # 사용자 3
    [-1, 0, 0, 1]   # 사용자 4
])

# 실제 값 (평가가 없던 아이템에 대한 실제 값, NaN으로 평가 없음 표시)
actual_values = np.array([
    [np.nan, 1, np.nan, -1],  # 사용자 1에 대한 실제 값
    [1, np.nan, 1, 1],        # 사용자 2에 대한 실제 값
    [-1, 1, 1, np.nan],        # 사용자 3에 대한 실제 값
    [np.nan, 1, 1, 1]         # 사용자 4에 대한 실제 값
])

# 코사인 유사도 계산 함수
def cosine_similarity(matrix):
    item_count = matrix.shape[1]
    similarity_matrix = np.zeros((item_count, item_count))

    for i in range(item_count):
        for j in range(item_count):
            if i == j:
                similarity_matrix[i, j] = 1  # 자기 자신과의 유사도는 1
            else:
                dot_product = np.dot(matrix[:, i], matrix[:, j])
                norm_i = np.linalg.norm(matrix[:, i])
                norm_j = np.linalg.norm(matrix[:, j])
                
                if norm_i > 0 and norm_j > 0:
                    similarity_matrix[i, j] = dot_product / (norm_i * norm_j)
                else:
                    similarity_matrix[i, j] = 0

    return similarity_matrix

# 선호 예측 함수
def predict_preferences(user_item_matrix, similarity_matrix):
    predictions = np.zeros_like(user_item_matrix)
    predicted_values = []  # 예측된 값 리스트
    actual_values_list = []  # 실제 값 리스트

    for user in range(user_item_matrix.shape[0]):
        for item in range(user_item_matrix.shape[1]):
            if user_item_matrix[user, item] != 0:  # 평가가 있는 경우는 건너뜀
                continue

            # 평가가 없는 경우에 대해 예측
            similar_items = similarity_matrix[item]
            weighted_sum = np.dot(similar_items, user_item_matrix[user, :])
            normalization_factor = np.sum(np.abs(similar_items[similar_items > 0]))  # 가중치의 합
            if normalization_factor > 0:
                prediction = weighted_sum / normalization_factor
                # 예측값을 1 또는 -1로 변환
                predicted_value = 1 if prediction > 0 else -1
                predictions[user, item] = predicted_value
                
                # 리스트에 예측값과 실제값 저장
                predicted_values.append(predicted_value)
                # 실제 값이 NaN이 아닐 경우에만 저장
                actual_value = actual_values[user, item]
                if not np.isnan(actual_value):
                    actual_values_list.append(actual_value)

    return predictions, predicted_values, actual_values_list

# 정확도 계산 함수
def calculate_accuracy(predicted_values, actual_values_list):
    correct_predictions = sum(p == a for p, a in zip(predicted_values, actual_values_list))
    total_predictions = len(actual_values_list)

    if total_predictions == 0:
        return 0  # 평가가 없으면 정확도 0
    return correct_predictions / total_predictions

# 코사인 유사도 행렬 생성
similarity_matrix = cosine_similarity(user_item_matrix)

# 선호 예측 수행
predictions, predicted_values, actual_values_list = predict_preferences(user_item_matrix, similarity_matrix)

# 정확도 계산
accuracy = calculate_accuracy(predicted_values, actual_values_list)

# 결과 출력
print("코사인 유사도 행렬:")
print(similarity_matrix)
print("예측된 선호도 행렬:")
print(predictions)
print("예측된 값 리스트:", predicted_values)
print("실제 값 리스트:", actual_values_list)
print(f"정확도: {accuracy:.2f}")

코사인 유사도 행렬:
[[ 1.         -0.40824829 -0.40824829  0.        ]
 [-0.40824829  1.          0.5        -0.5       ]
 [-0.40824829  0.5         1.          0.        ]
 [ 0.         -0.5         0.          1.        ]]
예측된 선호도 행렬:
[[ 0 -1  0 -1]
 [ 0  0 -1  0]
 [-1  0  0 -1]
 [ 0 -1  1  0]]
예측된 값 리스트: [-1, -1, -1, -1, -1, -1, 1]
실제 값 리스트: [1.0, -1.0, 1.0, -1.0, 1.0, 1.0]
정확도: 0.33


In [11]:
import numpy as np

# 사용자-아이템 행렬 (1: 선호, -1: 비선호, np.nan: 평가 없음, 0: validation)
user_item_matrix = np.array([
    [1, 0, -1, np.nan],  # 사용자 1
    [1, -1, np.nan, 1],        # 사용자 2
    [0, 1, 1, np.nan],    # 사용자 3
    [-1, 0, 0, 1]    # 사용자 4
])


# 실제 값 (평가가 없던 아이템에 대한 실제 값, np.nan으로 평가 없음 표시)
actual_values = np.array([
    [1, 1, -1, np.nan],  # 사용자 1에 대한 실제 값
    [1, -1, np.nan, 1],        # 사용자 2에 대한 실제 값
    [np.nan, 1, 1, np.nan],        # 사용자 3에 대한 실제 값
    [-1, np.nan, 1, 1]         # 사용자 4에 대한 실제 값
])

# 코사인 유사도 계산 함수
def cosine_similarity(matrix):
    item_count = matrix.shape[1]
    similarity_matrix = np.zeros((item_count, item_count))

    for i in range(item_count):
        for j in range(item_count):
            if i == j:
                similarity_matrix[i, j] = 1  # 자기 자신과의 유사도는 1
            else:
                # NaN을 제외한 벡터를 생성
                valid_indices = ~np.isnan(matrix[:, i]) & ~np.isnan(matrix[:, j])
                if np.any(valid_indices):
                    dot_product = np.dot(matrix[valid_indices, i], matrix[valid_indices, j])
                    norm_i = np.linalg.norm(matrix[valid_indices, i])
                    norm_j = np.linalg.norm(matrix[valid_indices, j])
                    
                    if norm_i > 0 and norm_j > 0:
                        similarity_matrix[i, j] = dot_product / (norm_i * norm_j)
                else:
                    similarity_matrix[i, j] = 0

    return similarity_matrix

# 선호 예측 함수
def predict_preferences(user_item_matrix, similarity_matrix):
    predictions = np.zeros_like(user_item_matrix)
    predicted_values = []  # 예측된 값 리스트
    actual_values_list = []  # 실제 값 리스트

    for user in range(user_item_matrix.shape[0]):
        for item in range(user_item_matrix.shape[1]):
            if user_item_matrix[user, item] != 0:  # 평가가 0인 경우에 대해서만 예측
                continue

            # 평가가 0인 경우에 대해 예측
            similar_items = similarity_matrix[item]
            weighted_sum = np.dot(similar_items, user_item_matrix[user, :])
            normalization_factor = np.sum(np.abs(similar_items[similar_items > 0]))  # 가중치의 합
            if normalization_factor > 0:
                prediction = weighted_sum / normalization_factor
                # 예측값을 1 또는 -1로 변환
                predicted_value = 1 if prediction > 0 else -1
                predictions[user, item] = predicted_value
                
                # 리스트에 예측값과 실제값 저장
                predicted_values.append(predicted_value)
                # 실제 값이 NaN이 아닐 경우에만 저장
                actual_value = actual_values[user, item]
                if not np.isnan(actual_value):
                    actual_values_list.append(actual_value)

    return predictions, predicted_values, actual_values_list

# 정확도 계산 함수
def calculate_accuracy(predicted_values, actual_values_list):
    correct_predictions = sum(p == a for p, a in zip(predicted_values, actual_values_list))
    total_predictions = len(actual_values_list)

    if total_predictions == 0:
        return 0  # 평가가 없으면 정확도 0
    return correct_predictions / total_predictions

# 코사인 유사도 행렬 생성
similarity_matrix = cosine_similarity(user_item_matrix)

# 선호 예측 수행
predictions, predicted_values, actual_values_list = predict_preferences(user_item_matrix, similarity_matrix)

# 정확도 계산
accuracy = calculate_accuracy(predicted_values, actual_values_list)

# 결과 출력
print("코사인 유사도 행렬:")
print(similarity_matrix)
print("예측된 선호도 행렬:")
print(predictions)
print("예측된 값 리스트:", predicted_values)
print("실제 값 리스트:", actual_values_list)
print(f"정확도: {accuracy:.2f}")


코사인 유사도 행렬:
[[ 1.         -0.40824829 -0.5         0.        ]
 [-0.40824829  1.          0.70710678 -0.70710678]
 [-0.5         0.70710678  1.          0.        ]
 [ 0.         -0.70710678  0.          1.        ]]
예측된 선호도 행렬:
[[ 0. -1.  0.  0.]
 [ 0.  0.  0.  0.]
 [-1.  0.  0.  0.]
 [ 0. -1.  1.  0.]]
예측된 값 리스트: [-1, -1, -1, 1]
실제 값 리스트: [1.0, 1.0]
정확도: 0.00
